### ISSUE TITLE
3rd CAN interrupt?

### ISSUE THREAD

**Issue by tz1** [CANBus-Triple/CANBus-Triple#1]
I've finally forked and am refactoring a simpler I/O version only of the code, and noticed there was an interrupt only for the first two chips (not used in the writing).  Is there an interrupt for the 3rd chip?  Also schematics or something similar with the hardware details would be helpful.  When my code does something useful I'll contribute it back.

**Comment by etx** [comment]
Great!

When designing the board I misunderstood something along the lines and thought the 32u4 had only 2 interrupts. I _think_ you could add an air wire to the correct pin from the MCP2515 Interrupt pin. I'd have to check the schematic again when I get home to verify they are not in use. 

In the new hardware PD3 and PD2 are used for serial to the bluetooth module and PD0, PD1, PE6 will most likely be for interrupts from each 2515.

**Comment by Tuckie** [comment]
@etx: I'm interested in purchasing one from your store... which version of the hardware would I get?

**Comment by etx** [comment]
@Tuckie We only have one version :) Well, we have some different colored enclosures but they are sold out ATM.
