### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by shawnl** [CANBus-Triple/CANBus-Triple#27]
This is the error I am getting. This is with a Nissan Versa 2009

{"event":"busdbg", "name":"Bus 1", "canctrl":"4", "status":"0", "error":"B", "errorText":"Receive Error Warning - TEC or REC >= 96, Receive Error Warning - REC >= 96, Receive Error Warning - REC >= 128, ", "nextTxBuffer":"0"}

**Comment by jrmunson** [comment]
I. Think the error 'B' is a bit rate issue. Try running auto baud on bus 1

Jim Munson
LinkedIn.com/in/JamesMunson

On Jul 11, 2015, at 5:31 PM, Shawn Landden notifications@github.com wrote:

This is the error I am getting. This is with a Nissan Versa 2009

{"event":"busdbg", "name":"Bus 1", "canctrl":"4", "status":"0", "error":"B", "errorText":"Receive Error Warning - TEC or REC >= 96, Receive Error Warning - REC >= 96, Receive Error Warning - REC >= 128, ", "nextTxBuffer":"0"}

**Comment by shawnl** [comment]
That worked.
