### ISSUE TITLE
CAN Message queues are limited to only 2 elements!

### ISSUE THREAD

**Issue by eiannone** [CANBus-Triple/CANBus-Triple#33]
I think to have found a flaw in the CAN frames queue management.
Looking at [QueueArray.h](/CANBus-Triple/CANBus-Triple/blob/master/avr/libraries/QueueArray/QueueArray.h), the class used for managing CAN messages read and written from/to CAN busses, I realized that it's built with an [initial size of 2 elements](/CANBus-Triple/CANBus-Triple/blob/master/avr/libraries/QueueArray/QueueArray.h#L97), which should automatically grow when pushing more items into it, but in CANBus-Triple this never happens because, before pushing a new message, it checks if the queue is full and in that case it doesn't push any message but discards it, as you can see in readMsgFromBuffer() function (see for example [here ](/CANBus-Triple/CANBus-Triple/blob/master/avr/examples/CANBusTriple/CANBusTriple.ino#L198)and [here](/CANBus-Triple/CANBus-Triple/blob/master/avr/examples/CANBusTriple/CANBusTriple.ino#L146)).
So we are indeed using the read and write queues with a capacity of only 2 elements!
This could lead to missing CAN frames, especially when reading/writing to/from more than one bus at the same time (see for example the discussion at 412f064eabfdf0e1129631bc5668bea40b1ef0d6).

I've made some code changes, replacing the QueueArray class with a new class QueueMessage written from scratch, that could solve this problem, being also more efficient.
It defines read and write queues with a fixed (configurable) size, allocated statically.
I'll submit a PR shortly to fix the issue.

P.S. @etx , I cannot log to canb.us forum, neither reset my password, because I'm not receiving the emails sent from your server. Could you please check it? thank you.

**Comment by etx** [comment]
Great work! I'll give this a shot asap.

I remember testing the queue size and getting up to 32 entries before I ran out of ram. But perhaps I messed it up while optimizing the code. 

Thanks for your contributions, I'll report back after testing!

Ill check the forum setup as well. The email was working. Maybe it's landing in your spam box?

**Comment by eiannone** [comment]
I've found some problems with last commit of my PR, especially when sending CAN packets. On the next days I'll investigate more and try to fix them.

As to forum password reset, I didn't find any email in my spam folder. I've tried also disabling antispam filter but still didn't receive any. I also tried to register again using a different email address (gmail), but I have not received anything.

**Comment by eiannone** [comment]
Problem should be fixed now

**Comment by etx** [comment]
Thanks! looks good, I'm going to run some more tests before I merge. 

I just updated the forum software and modules. Test emails are coming through to my personal gmail account fine. Let me know if it works for you.

**Comment by etx** [comment]
Tested and merged. Great work, you rock!
